name: build
# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  contents: read # WTF 1: https://github.com/actions/checkout/issues/254#issuecomment-1632353441
  checks: write # WTF 2: https://github.com/mikepenz/action-junit-report/issues/23#issuecomment-1412597753
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.actor == 'vsuharnikov'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_386.tar.gz -o ghcli.tar.gz
          tar xvf ghcli.tar.gz
          mv gh_2.32.1_linux_386/bin/gh ./

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jre

      - name: Download JAR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          ./gh release download --repo ${{ github.repository }} --pattern "waves-ride-runner-*.jar"

      - name: Run tests
        run: |
          shopt -s globstar
          java -jar waves-ride-runner-*.jar test -p text --printTotal --junit build/test-results/all.xml tests/**/*.conf

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'build/test-results/all.xml'
