name: build
# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  contents: read # WTF 1: https://github.com/actions/checkout/issues/254#issuecomment-1632353441
  checks: write # WTF 2: https://github.com/mikepenz/action-junit-report/issues/23#issuecomment-1412597753
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.actor == 'vsuharnikov'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs tests
      # - name: Run a one-line script
      #  run: echo Hello, world!

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/all.xml'

#      - name: Upload Test Report
#        uses: actions/upload-artifact@v3
#        with:
#          name: junit-test-results
#          path: '**/build/test-results/all.xml'
#          retention-days: 1

