name: build
# Controls when the workflow will run
on:
  workflow_dispatch:

# https://github.com/marketplace/actions/junit-report-action#user-content-pr-run-permissions
permissions:
  contents: read
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.actor == 'vsuharnikov'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs tests
      # - name: Run a one-line script
      #  run: echo Hello, world!

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: '**/build/test-results/all.xml'
          retention-days: 1
