# This is a basic workflow to help you get started with Actions

name: build
# Controls when the workflow will run
on:
  workflow_dispatch:

# https://github.com/marketplace/actions/junit-report-action#user-content-pr-run-permissions
permissions:
  checks: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.actor == 'vsuharnikov'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs tests
      # - name: Run a one-line script
      #  run: echo Hello, world!

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: '**/build/test-results/all.xml'
          retention-days: 1

#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v3
#        with:
#          report_paths: '**/build/test-results/all.xml'

---
name: report
on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/test/all.xml'
